"""
Django settings for a Django project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
"""
Django settings for the website project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import sys
import logging

# ---------------------------------------------------------------------
# Base Paths & DLL Setup (for GeoDjango on Windows)
# ---------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

CONDA_PREFIX = os.environ.get('CONDA_PREFIX') or r"C:\Users\maimo\miniconda3\envs\royalstep"
BIN_DIR = os.path.join(CONDA_PREFIX, "Library", "bin")

if sys.platform == "win32":
    if hasattr(os, "add_dll_directory"):
        try:
            os.add_dll_directory(BIN_DIR)
        except Exception:
            os.environ['PATH'] = BIN_DIR + os.pathsep + os.environ.get('PATH', '')
    else:
        os.environ['PATH'] = BIN_DIR + os.pathsep + os.environ.get('PATH', '')

# Paths for GeoDjango
GDAL_LIBRARY_PATH = os.path.join(BIN_DIR, "gdal.dll")
GEOS_LIBRARY_PATH = os.path.join(BIN_DIR, "geos_c.dll")

# ---------------------------------------------------------------------
# Core Django Settings
# ---------------------------------------------------------------------
SECRET_KEY = 'django-insecure-p2y_$kih#my=42h)tge)k@vy5-sdaagy_fbwm70-b#@bqc=dg+'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',         # GeoDjango
    'rest_framework',
    'rest_framework.authtoken',
    'tinymce',
    'pages.apps.PagesConfig',
    'blogs',
    "shop", 
    "django_filters", 
    "drf_spectacular"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        'USER': 'royalstep',
        'PASSWORD': 'royalstep-54',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ---------------------------------------------------------------------
# REST Framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'blogs.throttles.CommentAnonThrottle',
        'blogs.throttles.CommentUserThrottle',
        'blogs.throttles.ReactionAnonThrottle',
        'blogs.throttles.ReactionUserThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'comments_anon': '5/hour',
        'comments_user': '20/hour',
        'reactions_anon': '30/hour',
        'reactions_user': '100/hour',
    },
}

# ---------------------------------------------------------------------
# Internationalization & Timezone
# ---------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------
# Celery / Redis
# ---------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/1")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# ---------------------------------------------------------------------
# Static & Default Fields
# ---------------------------------------------------------------------
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------
# Caching (Redis)
# ---------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# ---------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'pages': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        }
    },
}
